# Configuration file which contains parameters for MQTT c++ sub/pub gateway

#port ssl: 18885, no ssl: 1883
#"tcp://localhost:1883"
#"ssl://localhost:18885"
## BROKER
server_address: "ssl://localhost:18885"

# Socket port gateway ---> system
socket_port_GS: 5000
# Socket port system ---> gateway
socket_port_SG: 5001


##This ID corresponds to the robot number among the other robots of the same type
## /!\ THIS HAS TO BE SET UP BY THE ADMINISTRATOR FOR THE MOMENT /!\
ID_entity: 1

##CLIENTS and RELATED PARAMATERS
clients:
  operator:
    name: "operator"
    ID_type: 0
    topic: "operator_t"
  niryo:
    name: "niryo"
    ID_type: 100
    topic: "niryo_t"
  turtlebot:
    name: "turtlebot"
    ID_type: 200
    topic: "turtlebot_t"
  isenbot:
    name: "isenbot"
    ID_type: 300
    topic: "isenbot_t"
  hexapod:
    name: "hexapod"
    ID_type: 400
    topic: "hexapod_t"
  server:
    name: "server"
    ID_type: 500
    topic: "server_t"

##Which ID to use in order to broadcast a message
ID_broadcast: 1000

##Quality Of Service
QOS: 1

TIMEOUT: 10

##Number of retries if connection lost before exit
N_RETRY_ATTEMPTS: 15
