# Configuration file which contains parameters for MQTT c++ sub/pub

#port ssl: 18885, no ssl: 1883
#"tcp://localhost:1883"
#"ssl://localhost:18885"
## BROKER
server_address: "ssl://localhost:18885"

##CLIENT
client_id1: "Device1"
client_id2: "Device2"


#créer une liste de topics pour chaque device de façon à ce que la gateway subscribe itérativement à chacun d'eux
##TOPICS
topic_server: "topic_server1"

##Quality Of Service
QOS: 1

TIMEOUT: 10

##Number of retries if connection lost before exit
N_RETRY_ATTEMPTS: 5
